name: Workflow A

on:
  push:
    branches: [ "main" ]
 
jobs:
  workflow_a:
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: Run a first steps
        run: echo "Hello, world!"
  producing_data:
    runs-on: ubuntu-latest
    steps:
      - name: create json file
        run: |
          printf '{
            "ec2_instance_id": "ec2_instance_id value",  
            "aws_region": "AWS_REGION"
            }' >> ec2_instance.json

      - name: Upload AWS EC2 Instance JSON Data
        uses: actions/upload-artifact@v4
        with:
          name: ec2_instance.json
          path: .